# Generated by Django 5.1.6 on 2025-02-17 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="assigned_lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_lawyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_to", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="CaseAssignment",
        ),
    ]
