# Generated by Django 5.1.6 on 2025-02-20 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_case_assigned_lawyer_alter_case_assigned_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="cases.case",
            ),
        ),
    ]
