# Generated by Django 5.1.6 on 2025-02-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_approved_by_case_estimated_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
