# Generated by Django 5.1.6 on 2025-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_timeentry_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
