# Generated by Django 5.1.6 on 2025-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
    ]
